# Generated by Django 3.2.7 on 2021-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('кг', 'кг'), ('гр', 'гр'), ('другое', 'другое')], default='другое', max_length=25),
        ),
    ]
