# Generated by Django 3.2.7 on 2021-10-14 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperequirement',
            options={'ordering': ['menu_item']},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
